name: geofence_service
description: This plugin is a geofence service with activity recognition API.
version: 3.4.0
author: WOO JIN HWANG <hwj930513@naver.com>
homepage: https://github.com/Dev-hwang/geofence_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^1.0.1
  vector_math: ^2.1.0
  flutter_foreground_task: ^3.0.0+1
  flutter_activity_recognition: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.geofence_service
        pluginClass: GeofenceServicePlugin
      ios:
        pluginClass: GeofenceServicePlugin
