name: geofence_service
description: This plugin is a geofence service with activity recognition API.
version: 5.0.0
homepage: https://github.com/Dev-hwang/geofence_service

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^3.0.0
  flutter_foreground_task: ^6.1.2
  flutter_activity_recognition: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.geofence_service
        pluginClass: GeofenceServicePlugin
      ios:
        pluginClass: GeofenceServicePlugin
